services:
  golangci-lint:
    build:
      dockerfile: docker/golangci/Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
  golang:
    build:
      dockerfile: docker/golang/Dockerfile
    volumes:
      - ./:/app
      - golang:/go
    working_dir: /app
    environment:
      TF_ACC: true
  hadolint:
    build:
      dockerfile: docker/hadolint/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
  shellcheck:
    build:
      dockerfile: docker/shellcheck/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
  node:
    build:
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
  prism_public_cloud:
    build:
      dockerfile: docker/prism/Dockerfile
    command: >
      mock -p 4010 --host 0.0.0.0
      ${PUBLIC_CLOUD_API_SPEC_URL}
    env_file:
      - path: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  prism_dedicated_server:
    build:
      dockerfile: docker/prism/Dockerfile
    command: >
      mock -p 4010 --host 0.0.0.0
      ${DEDICATED_SERVER_API_SPEC_URL}
    env_file:
      - path: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  prism-proxy:
    build:
      dockerfile: docker/caddy/Dockerfile
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "8080:80"
    depends_on:
      - prism_public_cloud
      - prism_dedicated_server

volumes:
  golang:
