services:
  prism_public_cloud:
    container_name: prism_public_cloud
    build:
      dockerfile: prism/Dockerfile
    command: >
      mock -p 4010 --host 0.0.0.0
      ${PUBLIC_CLOUD_API_SPEC_URL}
    env_file:
      - path: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  prism_dedicated_server:
    container_name: prism_dedicated_server
    build:
      dockerfile: prism/Dockerfile
    command: >
      mock -p 4010 --host 0.0.0.0
      ${DEDICATED_SERVER_API_SPEC_URL}
    env_file:
      - path: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  prism_dns:
    container_name: prism_dns
    build:
      dockerfile: prism/Dockerfile
    command: >
      mock -p 4010 --host 0.0.0.0
      ${DNS_API_SPEC_URL}
    env_file:
      - path: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  prism_ipmgmt:
    container_name: prism_ipmgmt
    build:
      dockerfile: docker/prism/Dockerfile
    command: >
      mock -p 4010 --host 0.0.0.0
      ${IPMGMT_API_SPEC_URL}
    env_file:
      - path: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  prism-proxy:
    build:
      dockerfile: caddy/Dockerfile
    volumes:
      - ./caddy/prism/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "8080:80"
    depends_on:
      - prism_public_cloud
      - prism_dedicated_server
      - prism_dns
      - prism_ipmgmt
