#!/usr/bin/env sh

pnpm run prettier:lint .
pnpm run markdown:lint .

docker-compose run --rm -T hadolint hadolint docker/golang/Dockerfile
docker-compose run --rm -T hadolint hadolint docker/node/Dockerfile

docker-compose run --rm -T shellcheck -x ./.husky/pre-commit
docker-compose run --rm -T shellcheck -x ./.husky/pre-push
docker-compose run --rm -T shellcheck -x ./.husky/commit-msg

golangci-lint run
go mod download && go build -v .
go test -v -cover ./internal/provider/


