on:
  push:
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_names: import.sh
